### Create new question
POST http://localhost:8080/api/questions
Content-Type: application/json

{
  "behavioralIndicatorId": "{{behavioralIndicatorId}}",
  "text": "Example question text",
  "answerOptions": [
    {
      "label": "Option 1",
      "value": 1
    },
    {
      "label": "Option 2",
      "value": 2
    }
  ]
}
