### Удалить компетенцию по ID
DELETE http://localhost:8080/api/competencies/3d0c8f56-eb48-4770-83f5-76b7bc451d5e

### Удалить несуществующую компетенцию - Тест на ошибку
DELETE http://localhost:8080/api/competencies/00000000-0000-0000-0000-000000000000
