### Update existing competency
PUT http://localhost:8080/api/competencies/{{competencyId}}
Content-Type: application/json

{
  "name": "Updated Competency Name",
  "description": "Updated description of the competency"
}
